"""
Process file use case.

Extracts symbols, references, comments, dependencies, and text content from
a single file during indexing. Uses content-addressable file versioning: if a
file version (repo, path, content_hash) already exists, skips parsing entirely.
"""

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from inxr2.domain.entities import (
    Dependency,
    Reference,
    Symbol,
    TextContent,
)
from inxr2.domain.services.language_detector import LanguageDetector
from inxr2.domain.value_objects import (
    ReferenceType,
    SymbolKind,
    TextSearchSourceType,
)

from ...ports.repositories import (
    DependencyRepositoryPort,
    FileRepositoryPort,
    ReferenceRepositoryPort,
    SymbolRepositoryPort,
    TextContentRepositoryPort,
)
from ...ports.services import (
    DependencyParserServicePort,
    GitServicePort,
    ParserServicePort,
    PlaintextParserPort,
)

logger = logging.getLogger(__name__)

# PostgreSQL tsvector has a hard limit of 1,048,575 bytes on the *generated*
# tsvector, which can be larger than the input text due to positional data
# and lexeme overhead. We use a conservative limit to account for this.
MAX_TSVECTOR_CONTENT_BYTES = 750_000


def truncate_for_tsvector(content: str) -> tuple[str, bool]:
    """Cap input content to reduce the risk of PostgreSQL tsvector overflow.

    The tsvector generated by PostgreSQL can be larger than the input text
    (due to lexemes, positional data, etc.), so this is a conservative
    input-byte cap, not a strict tsvector size guarantee. Truncates on a
    UTF-8 byte boundary so multi-byte characters are never split.

    Returns:
        Tuple of (possibly truncated content, whether truncation occurred).
    """
    encoded = content.encode("utf-8")
    if len(encoded) <= MAX_TSVECTOR_CONTENT_BYTES:
        return content, False
    # Truncate the raw bytes, then decode ignoring any trailing partial character
    truncated = encoded[:MAX_TSVECTOR_CONTENT_BYTES]
    return truncated.decode("utf-8", errors="ignore"), True


@dataclass
class ProcessFileRequest:
    """Request to process a single file during indexing."""

    repository_id: int
    file_path: str
    commit_hash: str
    repo_path: Path
    blob_hash: str | None = None  # git blob hash for fast skip
    blob_to_content_hash: dict[str, str] | None = None  # blob hash -> content hash
    # Pre-loaded index: (path, content_hash) -> file_id.
    # When provided, skips individual DB queries for cached file versions.
    file_version_index: dict[tuple[str, str], int] | None = None


@dataclass
class ProcessFileResult:
    """Result of processing a single file."""

    processed: bool
    skipped: bool
    failed: bool
    file_id: int | None  # file version ID for commit_files linking
    file_version_created: bool  # True if a new file version was created
    symbols_found: int
    references_found: int
    lines_indexed: int
    comments_indexed: int
    docstrings_indexed: int
    dependencies_found: int
    non_code_file_indexed: bool
    error: str | None = None


def _cached_result(file_id: int) -> ProcessFileResult:
    """Return a result for a cached (already-existing) file version."""
    return ProcessFileResult(
        processed=True,
        skipped=False,
        failed=False,
        file_id=file_id,
        file_version_created=False,
        symbols_found=0,
        references_found=0,
        lines_indexed=0,
        comments_indexed=0,
        docstrings_indexed=0,
        dependencies_found=0,
        non_code_file_indexed=False,
    )


@dataclass
class _FileResolution:
    """Result of resolving a file's content and version."""

    file_id: int
    content: str
    language: str | None
    line_count: int
    created: bool
    cached: bool  # True if file version already existed (no parsing needed)


class ProcessFileUseCase:
    """
    Use case for processing a single file during indexing.

    Uses content-addressable file versioning:
    - A file version is uniquely identified by (repo_id, path, content_hash)
    - If a version already exists, we skip parsing entirely (no copying needed)
    - If it's new, we parse and save symbols/references
    - The caller (ProcessCommitUseCase) handles linking file_id to commit
    """

    def __init__(
        self,
        git_service: GitServicePort,
        file_repo: FileRepositoryPort,
        symbol_repo: SymbolRepositoryPort,
        reference_repo: ReferenceRepositoryPort,
        text_content_repo: TextContentRepositoryPort,
        parser_service: ParserServicePort,
        plaintext_parser: PlaintextParserPort,
        dependency_parser: DependencyParserServicePort | None = None,
        dependency_repo: DependencyRepositoryPort | None = None,
    ) -> None:
        self._git_service = git_service
        self._file_repo = file_repo
        self._symbol_repo = symbol_repo
        self._reference_repo = reference_repo
        self._text_content_repo = text_content_repo
        self._parser_service = parser_service
        self._plaintext_parser = plaintext_parser
        self._dependency_parser = dependency_parser
        self._dependency_repo = dependency_repo

    async def execute(self, request: ProcessFileRequest) -> ProcessFileResult:
        """Process a single file: find or create version, parse if new."""
        try:
            return await self._do_process(request)
        except Exception as e:  # Catch-all: resilience boundary for per-file processing
            return ProcessFileResult(
                processed=False,
                skipped=False,
                failed=True,
                file_id=None,
                file_version_created=False,
                symbols_found=0,
                references_found=0,
                lines_indexed=0,
                comments_indexed=0,
                docstrings_indexed=0,
                dependencies_found=0,
                non_code_file_indexed=False,
                error=f"Failed to process {request.file_path}: {e}",
            )

    async def _do_process(self, request: ProcessFileRequest) -> ProcessFileResult:
        """Inner processing logic."""
        resolution = await self._resolve_file_version(request)
        if resolution.cached:
            return _cached_result(resolution.file_id)

        file_id = resolution.file_id
        content = resolution.content
        language = resolution.language
        line_count = resolution.line_count

        # Parse dependencies if this is a manifest/lock file
        dependencies_found = await self._extract_and_save_dependencies(
            content=content,
            file_path_str=request.file_path,
            repository_id=request.repository_id,
            file_id=file_id,
        )

        # Parse and save symbols/references for supported code files
        if language and self._parser_service.supports_language(language):
            symbols_data, references_data = await self._parser_service.parse_file(
                content=content,
                language=language,
                file_path=request.file_path,
            )

            comments_indexed, docstrings_indexed, comment_errors = (
                await self._extract_and_save_comments(
                    content=content,
                    language=language,
                    file_path_str=request.file_path,
                    repository_id=request.repository_id,
                    file_id=file_id,
                )
            )

            symbols_found = await self._extract_and_save_symbols(
                symbols_data=symbols_data,
                repository_id=request.repository_id,
                file_id=file_id,
                file_path_str=request.file_path,
            )

            references_found = await self._extract_and_save_references(
                references_data=references_data,
                repository_id=request.repository_id,
                file_id=file_id,
            )

            return ProcessFileResult(
                processed=True,
                skipped=False,
                failed=False,
                file_id=file_id,
                file_version_created=True,
                symbols_found=symbols_found,
                references_found=references_found,
                lines_indexed=line_count,
                comments_indexed=comments_indexed,
                docstrings_indexed=docstrings_indexed,
                dependencies_found=dependencies_found,
                non_code_file_indexed=False,
                error=comment_errors,
            )

        # Not a supported code file — try parsing as plaintext/non-code file
        indexed_as_plaintext = await self._index_non_code_file(
            content=content,
            file_path_str=request.file_path,
            repository_id=request.repository_id,
            file_id=file_id,
        )

        if indexed_as_plaintext.indexed:
            return ProcessFileResult(
                processed=True,
                skipped=False,
                failed=False,
                file_id=file_id,
                file_version_created=True,
                symbols_found=0,
                references_found=0,
                lines_indexed=line_count,
                comments_indexed=0,
                docstrings_indexed=0,
                dependencies_found=dependencies_found,
                non_code_file_indexed=True,
                error=indexed_as_plaintext.error,
            )

        # File wasn't code and wasn't plaintext-indexed, but may still
        # have been a manifest file (e.g. pom.xml is XML, not "code")
        return ProcessFileResult(
            processed=dependencies_found > 0,
            skipped=dependencies_found == 0,
            failed=False,
            file_id=file_id,
            file_version_created=True,
            symbols_found=0,
            references_found=0,
            lines_indexed=0,
            comments_indexed=0,
            docstrings_indexed=0,
            dependencies_found=dependencies_found,
            non_code_file_indexed=False,
        )

    async def _resolve_file_version(
        self, request: ProcessFileRequest
    ) -> _FileResolution:
        """Retrieve file content, compute hash, and find or create file version.

        Checks multiple cache layers (blob hash, file version index, DB) to
        avoid redundant content reads and parsing. Returns a cached resolution
        if the file version already exists.
        """
        fvi = request.file_version_index

        # Fast path 1: blob hash → content hash → file_version_index lookup
        # Avoids BOTH git content read AND DB query.
        known_content_hash = self._lookup_blob_hash(request)
        if known_content_hash:
            # Check in-memory index first (O(1) dict lookup)
            if fvi is not None:
                cached_id = fvi.get((request.file_path, known_content_hash))
                if cached_id is not None:
                    return _FileResolution(
                        file_id=cached_id,
                        content="",
                        language=None,
                        line_count=0,
                        created=False,
                        cached=True,
                    )
            # Fallback to DB query
            existing_files = await self._file_repo.find_by_content_hash(
                known_content_hash,
                repository_id=request.repository_id,
                path=request.file_path,
            )
            existing_version = existing_files[0] if existing_files else None
            if existing_version is not None:
                return _FileResolution(
                    file_id=existing_version.id,  # type: ignore[arg-type]
                    content="",
                    language=None,
                    line_count=0,
                    created=False,
                    cached=True,
                )
            # Not found — fall through to full processing

        # Read file content from git
        content = self._git_service.get_file_content(
            repo_path=request.repo_path,
            commit_hash=request.commit_hash,
            file_path=request.file_path,
        )

        # Calculate content hash
        content_hash = hashlib.sha1(content.encode("utf-8")).hexdigest()

        # Record blob → content hash mapping for future fast skip
        if request.blob_hash and request.blob_to_content_hash is not None:
            request.blob_to_content_hash[request.blob_hash] = content_hash

        # Fast path 2: check file_version_index after computing content hash
        if fvi is not None:
            cached_id = fvi.get((request.file_path, content_hash))
            if cached_id is not None:
                return _FileResolution(
                    file_id=cached_id,
                    content="",
                    language=None,
                    line_count=0,
                    created=False,
                    cached=True,
                )

        # Detect language
        language = LanguageDetector.detect(request.file_path)
        if language is None and content:
            first_line = content.split("\n", 1)[0]
            language = LanguageDetector.detect_from_shebang(first_line)

        extension = Path(request.file_path).suffix.lower() or None
        content_bytes = content.encode("utf-8")
        line_count = content.count("\n") + 1

        file_entity, created = await self._file_repo.find_or_create_version(
            repository_id=request.repository_id,
            path=request.file_path,
            content_hash=content_hash,
            size_bytes=len(content_bytes),
            language=language,
            extension=extension,
            line_count=line_count,
        )
        file_id = file_entity.id
        assert file_id is not None

        # Register newly created file in the index for subsequent lookups
        if created and fvi is not None:
            fvi[(request.file_path, content_hash)] = file_id

        return _FileResolution(
            file_id=file_id,
            content=content,
            language=language,
            line_count=line_count,
            created=created,
            cached=not created,
        )

    async def _extract_and_save_symbols(
        self,
        symbols_data: list[dict[str, Any]],
        repository_id: int,
        file_id: int,
        file_path_str: str,
    ) -> int:
        """Filter, build, and persist symbol entities.

        Skips symbols with empty names (can happen with macro-heavy code
        where tree-sitter produces empty identifiers). Returns the count
        of symbols saved.
        """
        valid_symbols_data = []
        for sd in symbols_data:
            if sd.get("name"):
                valid_symbols_data.append(sd)
            else:
                logger.debug(
                    "Skipping symbol with empty name at line %d in %s",
                    sd.get("start_line", 0),
                    file_path_str,
                )

        symbols = [
            Symbol(
                id=None,
                file_id=file_id,
                repository_id=repository_id,
                name=symbol_data["name"],
                kind=SymbolKind(symbol_data["kind"]),
                start_line=symbol_data["start_line"],
                start_column=symbol_data["start_column"],
                end_line=symbol_data["end_line"],
                end_column=symbol_data["end_column"],
                parent_symbol_id=symbol_data.get("parent_symbol_id"),
                scope=symbol_data.get("scope"),
                qualified_name=symbol_data.get("qualified_name"),
                signature=symbol_data.get("signature"),
                metadata=symbol_data.get("metadata", {}),
            )
            for symbol_data in valid_symbols_data
        ]
        if symbols:
            saved_symbols = await self._symbol_repo.save_many(symbols)
            await self._resolve_parent_symbol_ids(saved_symbols)
        return len(symbols)

    async def _extract_and_save_references(
        self,
        references_data: list[dict[str, Any]],
        repository_id: int,
        file_id: int,
    ) -> int:
        """Build and persist reference entities. Returns the count saved."""
        references = []
        for ref_data in references_data:
            reference_text = ref_data.get("text") or ref_data.get("reference_text", "")
            reference_type = ref_data.get("type") or ref_data.get(
                "reference_type", "usage"
            )
            source_column = ref_data["source_column"]
            source_end_column = ref_data.get(
                "source_end_column",
                source_column + len(reference_text),
            )

            references.append(
                Reference(
                    id=None,
                    repository_id=repository_id,
                    source_file_id=file_id,
                    source_line=ref_data["source_line"],
                    source_column=source_column,
                    source_end_column=source_end_column,
                    reference_text=reference_text,
                    reference_type=ReferenceType(reference_type),
                    target_symbol_id=None,
                )
            )
        if references:
            await self._reference_repo.save_many(references)
        return len(references)

    @staticmethod
    def _lookup_blob_hash(request: ProcessFileRequest) -> str | None:
        """Look up content hash from blob hash if available."""
        if (
            request.blob_hash
            and request.blob_to_content_hash is not None
            and request.blob_hash in request.blob_to_content_hash
        ):
            return request.blob_to_content_hash[request.blob_hash]
        return None

    async def _extract_and_save_dependencies(
        self,
        content: str,
        file_path_str: str,
        repository_id: int,
        file_id: int,
    ) -> int:
        """Extract dependencies from manifest/lock files and save to database.

        Returns the number of dependencies found and saved.
        """
        if self._dependency_parser is None or self._dependency_repo is None:
            return 0

        if not self._dependency_parser.supports_file(file_path_str):
            return 0

        try:
            dep_dicts = self._dependency_parser.parse(content, file_path_str)
            if not dep_dicts:
                return 0

            entities = [
                Dependency(
                    file_id=file_id,
                    repository_id=repository_id,
                    package_name=d["package_name"],
                    language=d["language"],
                    version_spec=d.get("version_spec"),
                    resolved_version=d.get("resolved_version"),
                    dependency_type=d.get("dependency_type", "runtime"),
                    is_direct=d.get("is_direct", True),
                    extras=d.get("extras"),
                )
                for d in dep_dicts
            ]
            await self._dependency_repo.save_many(entities)
            return len(entities)

        except Exception as e:
            logger.warning(
                "Failed to extract dependencies from %s: %s",
                file_path_str,
                e,
            )
            return 0

    async def _resolve_parent_symbol_ids(self, saved_symbols: list[Symbol]) -> None:
        """Resolve scope strings to parent_symbol_id after save.

        Parsers set a ``scope`` string (e.g., "ClassName") on child symbols
        but cannot set ``parent_symbol_id`` because DB IDs are not available
        during parsing. This method matches each symbol's ``scope`` to the
        parent symbol's name or qualified_name within the same file and
        updates the FK in a single bulk query.
        """
        # Build lookup: name/qualified_name → symbol_id for potential parents
        name_to_id: dict[str, int] = {}
        for s in saved_symbols:
            assert s.id is not None
            # Top-level symbols (no scope) are reachable by name
            if s.scope is None:
                name_to_id[s.name] = s.id
            # All symbols with a qualified_name are reachable by it
            if s.qualified_name:
                name_to_id[s.qualified_name] = s.id

        # Match children: scope → parent_id
        updates: dict[int, int] = {}
        for s in saved_symbols:
            if s.scope and s.parent_symbol_id is None:
                parent_id = name_to_id.get(s.scope)
                if parent_id is not None:
                    assert s.id is not None
                    updates[s.id] = parent_id

        if updates:
            updated = await self._symbol_repo.update_parent_symbol_ids(updates)
            logger.debug(
                "Resolved %d parent_symbol_id links (%d attempted)",
                updated,
                len(updates),
            )

    async def _extract_and_save_comments(
        self,
        content: str,
        language: str,
        file_path_str: str,
        repository_id: int,
        file_id: int,
    ) -> tuple[int, int, str | None]:
        """Extract comments and docstrings from a file and save to database.

        File-derived text content uses commit_id=None since it belongs
        to the file version, not a specific commit.

        Returns:
            Tuple of (comments_indexed, docstrings_indexed, error_message_or_none)
        """
        comments_indexed = 0
        docstrings_indexed = 0
        try:
            comments_data = await self._parser_service.extract_comments(
                content=content,
                language=language,
                file_path=file_path_str,
            )

            text_contents: list[TextContent] = []
            for comment_data in comments_data:
                comment_content = comment_data.get("content", "")
                if not comment_content or not comment_content.strip():
                    continue

                comment_content, was_truncated = truncate_for_tsvector(comment_content)
                if was_truncated:
                    logger.warning(
                        "Truncated comment content in %s (line %d) "
                        "to fit tsvector limit (%d bytes)",
                        file_path_str,
                        comment_data.get("source_line", 0),
                        MAX_TSVECTOR_CONTENT_BYTES,
                    )

                content_type = comment_data.get("content_type", "single_line_comment")
                if content_type == "docstring":
                    source_type = TextSearchSourceType.DOCSTRING.value
                    docstrings_indexed += 1
                else:
                    source_type = TextSearchSourceType.COMMENT.value
                    comments_indexed += 1

                text_contents.append(
                    TextContent(
                        id=None,
                        repository_id=repository_id,
                        commit_id=None,  # file-derived, not commit-specific
                        source_type=source_type,
                        source_file_id=file_id,
                        source_line=comment_data["source_line"],
                        source_end_line=comment_data.get("source_end_line"),
                        content=comment_content,
                        language=language,
                        content_type=content_type,
                    )
                )
            if text_contents:
                await self._text_content_repo.save_batch(text_contents)

        except (UnicodeDecodeError, OSError, RuntimeError) as e:
            return (
                comments_indexed,
                docstrings_indexed,
                f"Failed to extract comments from {file_path_str}: {e}",
            )

        return comments_indexed, docstrings_indexed, None

    @dataclass
    class _NonCodeResult:
        indexed: bool
        inserts: int
        error: str | None = None

    async def _index_non_code_file(
        self,
        content: str,
        file_path_str: str,
        repository_id: int,
        file_id: int,
    ) -> _NonCodeResult:
        """Index non-code files (markdown, YAML, etc.) as searchable text content."""
        try:
            # Skip binary content (null bytes indicate binary data).
            # In production, binary files already fail at get_file_content()
            # with UnicodeDecodeError, but this guards edge cases.
            if "\x00" in content:
                return self._NonCodeResult(indexed=False, inserts=0)

            chunks = self._plaintext_parser.parse(content, file_path_str)
            if not chunks:
                return self._NonCodeResult(indexed=False, inserts=0)

            text_contents: list[TextContent] = []
            for chunk in chunks:
                chunk_content, was_truncated = truncate_for_tsvector(chunk["content"])
                if was_truncated:
                    logger.warning(
                        "Truncated text content in %s (line %d) "
                        "to fit tsvector limit (%d bytes)",
                        file_path_str,
                        chunk.get("source_line", 0),
                        MAX_TSVECTOR_CONTENT_BYTES,
                    )
                text_contents.append(
                    TextContent(
                        id=None,
                        repository_id=repository_id,
                        commit_id=None,  # file-derived, not commit-specific
                        source_type=TextSearchSourceType.FILE_CONTENT.value,
                        source_file_id=file_id,
                        source_line=chunk["source_line"],
                        source_end_line=chunk.get("source_end_line"),
                        content=chunk_content,
                        language=None,
                        content_type=chunk["content_type"],
                    )
                )
            if text_contents:
                await self._text_content_repo.save_batch(text_contents)

            return self._NonCodeResult(indexed=True, inserts=len(text_contents))

        except (UnicodeDecodeError, OSError, RuntimeError) as e:
            return self._NonCodeResult(
                indexed=False,
                inserts=0,
                error=f"Failed to index non-code file {file_path_str}: {e}",
            )
