"""Initial schema: core tables for repositories, commits, files, symbols, references, and index_status

Revision ID: edc605da5d0a
Revises:
Create Date: 2026-01-05 00:50:40.897045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edc605da5d0a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_branch", sa.String(length=100), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=True)
    op.create_table(
        "commits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("commit_hash", sa.CHAR(length=40), nullable=False),
        sa.Column("short_hash", sa.CHAR(length=7), nullable=False),
        sa.Column("parent_hashes", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("branch", sa.String(length=255), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=False),
        sa.Column("author_email", sa.String(length=255), nullable=False),
        sa.Column("committer_name", sa.String(length=255), nullable=False),
        sa.Column("committer_email", sa.String(length=255), nullable=False),
        sa.Column("author_date", sa.DateTime(), nullable=False),
        sa.Column("commit_date", sa.DateTime(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commits_commit_hash"), "commits", ["commit_hash"], unique=False
    )
    op.create_table(
        "index_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("last_indexed_commit", sa.CHAR(length=40), nullable=True),
        sa.Column("last_indexed_at", sa.DateTime(), nullable=True),
        sa.Column("indexing_started_at", sa.DateTime(), nullable=True),
        sa.Column("indexing_status", sa.String(length=50), nullable=False),
        sa.Column("total_commits_indexed", sa.Integer(), nullable=False),
        sa.Column("total_files_indexed", sa.Integer(), nullable=False),
        sa.Column("total_symbols_indexed", sa.Integer(), nullable=False),
        sa.Column("total_references_indexed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("indexer_version", sa.String(length=50), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_index_status_indexing_status"),
        "index_status",
        ["indexing_status"],
        unique=False,
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=40), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("encoding", sa.String(length=50), nullable=False),
        sa.Column("is_binary", sa.Boolean(), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_files_content_hash"), "files", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_files_language"), "files", ["language"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("qualified_name", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("start_column", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("end_column", sa.Integer(), nullable=False),
        sa.Column("parent_symbol_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("docstring", sa.Text(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("name_tsvector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_symbol_id"], ["symbols.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_symbols_kind"), "symbols", ["kind"], unique=False)
    op.create_index(op.f("ix_symbols_name"), "symbols", ["name"], unique=False)
    op.create_index(
        op.f("ix_symbols_qualified_name"), "symbols", ["qualified_name"], unique=False
    )
    op.create_table(
        "references",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("source_line", sa.Integer(), nullable=False),
        sa.Column("source_column", sa.Integer(), nullable=False),
        sa.Column("source_end_column", sa.Integer(), nullable=False),
        sa.Column("reference_text", sa.String(length=500), nullable=False),
        sa.Column("target_symbol_id", sa.Integer(), nullable=True),
        sa.Column("target_repository_id", sa.Integer(), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=False),
        sa.Column("is_definition", sa.Boolean(), nullable=False),
        sa.Column("is_write", sa.Boolean(), nullable=False),
        sa.Column("resolution_confidence", sa.Float(), nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["source_file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_repository_id"], ["repositories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["target_symbol_id"], ["symbols.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_references_reference_text"),
        "references",
        ["reference_text"],
        unique=False,
    )
    op.create_index(
        op.f("ix_references_reference_type"),
        "references",
        ["reference_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_references_reference_type"), table_name="references")
    op.drop_index(op.f("ix_references_reference_text"), table_name="references")
    op.drop_table("references")
    op.drop_index(op.f("ix_symbols_qualified_name"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_name"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_kind"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(op.f("ix_files_language"), table_name="files")
    op.drop_index(op.f("ix_files_content_hash"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_index_status_indexing_status"), table_name="index_status")
    op.drop_table("index_status")
    op.drop_index(op.f("ix_commits_commit_hash"), table_name="commits")
    op.drop_table("commits")
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
